name: Python Code Quality
description: Run isort, black, flake8, mypy and bandit checks

inputs:
  app_dir:
    description: 'Application source directory (e.g. src)'
    required: false
    default: 'src'
  python_version:
    description: 'Python version to use (e.g. 3.14)'
    required: false
    default: '3.14'

runs:
  using: 'composite'
  steps:

    - name: Code Quality - isort
      shell: bash
      run: |
        DIRS="${{ inputs.app_dir }}"
        [ -d "tests" ] && DIRS="$DIRS tests"
        python${{ inputs.python_version }} -m isort --check-only --settings-path pyproject.toml $DIRS

    - name: Code Quality - black
      shell: bash
      run: |
        DIRS="${{ inputs.app_dir }}"
        [ -d "tests" ] && DIRS="$DIRS tests"
        python${{ inputs.python_version }} -m black --check --config pyproject.toml $DIRS

    - name: Code Quality - flake8
      shell: bash
      run: |
        DIRS="${{ inputs.app_dir }}"
        [ -d "tests" ] && DIRS="$DIRS tests"
        python${{ inputs.python_version }} -m flake8 --toml-config pyproject.toml $DIRS

    - name: Code Quality - mypy
      shell: bash
      run: |
        python${{ inputs.python_version }} -m mypy --config-file pyproject.toml ${{ inputs.app_dir }}

    - name: Code Quality - bandit
      shell: bash
      run: |
        python${{ inputs.python_version }} -m bandit -c pyproject.toml -r ${{ inputs.app_dir }}
