# {
#  "apiVersion": apps/v1.0.0
#  "kind": "pr-check"
#  "stack": "java"
# }


name: Java API — PR Check [Caller]
run-name: "${{ github.actor }} | PR Check | ${{ github.ref_name }}"

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'docker/**'
      - '.github/workflows/**'
  workflow_dispatch:
    inputs:
      environment:
        description: "Selecione o ambiente de implantação"
        required: true
        default: 'development'
        type: environment

jobs:
  pr_check:
    name: PR Check
    uses: felipementel/gh-actions/.github/workflows/java-pr-check.yml@main
    with:
      environment: ${{ github.event_name == 'workflow_dispatch' && inputs.environment || 'development' }}
      java_version: ${{ vars.BUILD_VERSION }}
      java_distribution: ${{ vars.JAVA_DISTRIBUTION || 'temurin' }}
      project_base_dir: './src'
      main_project: 'myproject-api'
      tests_folder: 'tests'
      report_title: 'My Project API - PR'
      sonar_exclusions: ''
      image_name: ${{ github.event.repository.name }}
      openapi_folder: 'open-api'
      docker_file_full_path: 'docker/Dockerfile'
      docker_build_context: '.'
    permissions:
      security-events: write
      contents: write
      id-token: write
      packages: write
    secrets:
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      REGISTRY_PAT: ${{ secrets.REGISTRY_PAT }}
