name: Sanbox Console Dispatch ⚡
run-name: "${{ github.actor }} - ${{ github.run_id }}"

#Secrets on Caller: GITLEAKS_LICENSE, SNYK_TOKEN, SONAR_TOKEN, SONAR_PROJECT_KEY
#VARS on Caller: SONAR_ORGANIZATION
on:
  pull_request:
    branches:
      - main
    types:
      closed
    paths-ignore:
      - '**.md'
      - '.github/**'
      - 'docker/**'
      - 'docs/**'
  workflow_call:
    inputs:
      environment:
        type: string
        description: 'Environment to run the workflow'
        required: true
        default: 'DEV'
      git_leaks:
        type: boolean
        description: 'Run GitLeaks'
        required: false
        default: true
      sonar_qube:
        type: boolean
        description: 'Run SonarQube'
        required: false
        default: true
      unit_tests:
        type: boolean
        description: 'Run Unit Tests'
        required: false
        default: true
      snyk:
        type: boolean
        description: 'Snyk.io'
        required: false
        default: true
      msg_canal_deploy:
        type: string
        description: 'Message to be displayed in the summary'
        required: false
        default: 'Canal DEPLOY - O melhor canal sobre .NET, Azure, DevOps e IA'
      #build config
      dotnet_version:
        type: string
        description: '.NET Version'
        required: true
        default: 9.x
      project_base_dir:
        type: string
        description: 'Path to SLNX file'
        required: true
        default: ./src
      sln:
        type: string
        description: 'The SLNX full name. eg: DEPLOY.PROJECT.API.slnx'
        required: true
        default: ""
      main_project:
        type: string
        description: 'The main project. eg: DEPLOY.PROJECT.API'
        required: true
        default: ""
      report_title:
        type: string
        description: 'Message to be displayed in the unit test report title'
        required: true
        default: 'Canal DEPLOY'
      #build use
      sonar_exclusions:
        type: string
        description: 'Path to exclusion from sonar, like migrations. Use comma separation'
        required: true
        default: ""
      #push-image
      image_name:
        type: string
        description: 'Image name to publish at github packages'
        required: true
        default: ""
    secrets:
      SONAR_PROJECT_KEY:
        required: true
        description: 'Sonar Project Key'
      GITLEAKS_LICENSE:
        required: true
        description: 'Gitleaks License'
      SNYK_TOKEN:
        required: true
        description: 'Snyk Token'
      SONAR_TOKEN:
        required: true
        description: 'Sonar Token'
env:
  RED: '\033[0;31m'
  GREEN: '\033[0;32m'
  YELLOW: '\033[0;33m'
  BLUE: '\033[0;34m'
  RESET: '\033[0m'
  BOLD: '\033[1m'
  UNDERLINE: '\033[4m'
  BOLD_UNDERLINE: '\033[1;4m'
  BOLD_RED: '\033[1;31m'
  BOLD_GREEN: '\033[1;32m'
  BOLD_YELLOW: '\033[1;33m'
  BOLD_BLUE: '\033[1;34m'

jobs:
  build:
    name: Build
    environment: ${{ inputs.environment }}
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    outputs:
      tag_version: ${{ steps.get_version.outputs.TAG }}
      now: ${{ steps.get_env.outputs.NOW }}
      image_exists: ${{ steps.check_image_and_tag.outputs.IMAGE_EXISTS }}
    runs-on: ubuntu-latest
    timeout-minutes: 4
    permissions:
      contents: read
      security-events: write

    steps:
      - name: Get Environment
        id: get_env
        run: |
          echo "::warning::Environment ${{ inputs.environment }}"
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_OUTPUT

      - name: Sys - Checkout
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/checkout@main
        with:
          sparse_checkout: |
            src
            .github
            test
          sparse_checkout_cone_mode: false

      - name: Sys - Get-Version from csproj
        id: get_version
        shell: bash
        run: |
          csproj_path="${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj"

          # Extrair os valores
          version=$(sed -n 's/.*<Version>\(.*\)<\/Version>.*/\1/p' "$csproj_path")
          versionPrefix=$(sed -n 's/.*<VersionPrefix>\(.*\)<\/VersionPrefix>.*/\1/p' "$csproj_path")
          versionSuffix=$(sed -n 's/.*<VersionSuffix>\(.*\)<\/VersionSuffix>.*/\1/p' "$csproj_path")

          # Validar versão
          if [[ -z "$version" ]]; then
            echo -e "${RED}❌ Erro: A tag <Version> é obrigatória no arquivo .csproj"
            exit 1
          fi

          # Montar TAG
          tag="$version"
          if [[ -n "$versionPrefix" ]]; then
            tag="${versionPrefix}-${tag}"
            ColorTagPrefix="${GREEN}"
          else
            ColorTagPrefix="${YELLOW}"
          fi

          if [[ -n "$versionSuffix" ]]; then
            tag="${tag}-${versionSuffix}"
            ColorTagSuffix="${GREEN}"
          else
            ColorTagSuffix="${YELLOW}"
          fi

          echo "::group::🔍 Informações de versão extraídas"
          echo -e "📦${GREEN} Version: $version"
          echo -e "⬅️${ColorTagPrefix} Prefix: ${versionPrefix:-n/a}"
          echo -e "➡️${ColorTagSuffix} Suffix: ${versionSuffix:-n/a}"
          echo -e "🏷️${GREEN} TAG final: $tag"
          echo "::endgroup::"

          echo "TAG=$tag" >> "$GITHUB_OUTPUT"
          echo "VERSION=$version" >> "$GITHUB_OUTPUT"
          echo "VERSION_PREFIX=$versionPrefix" >> "$GITHUB_OUTPUT"
          echo "VERSION_SUFFIX=$versionSuffix" >> "$GITHUB_OUTPUT"

      - name: Sys - Setup .NET version ${{ inputs.dotnet_version }}
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/setup-dotnet@main
        with:
          dotnet_version: ${{ inputs.dotnet_version }}

      - name: 🎃 Install Coverage
        if: ${{ inputs.unit_tests }}
        run: |
          dotnet tool install --global dotnet-coverage
          dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: 🧱 Git Leaks
        uses: gitleaks/gitleaks-action@v2
        if: ${{ inputs.git_leaks }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_ENABLE_SUMMARY: true
          GITLEAKS_ENABLE_UPLOAD_ARTIFACT: true
          GITLEAKS_NOTIFY_USER_LIST: '@felipementel'

      - name: 🔐 Set up JDK 23 to use with SonarCloud
        if: ${{ inputs.sonar_qube }}
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/setup-java@main
        with:
          java_version: 23
          distribution: 'zulu'

      - name: 🔐 SonarCloud packages cache
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/cache@main
        if: ${{ inputs.sonar_qube }}
        with:
          path: ~/sonar/cache
          key: ${{ runner.os }}-sonar
          restore_keys: ${{ runner.os }}-sonar

      - name: 🔐 SonarCloud scanner cache
        id: cache_sonar_scanner
        if: ${{ inputs.sonar_qube }}
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/cache@main
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore_keys: ${{ runner.os }}-sonar-scanner

      - name: 🔐 SonarCloud scanner installer
        if: ${{ inputs.sonar_qube }} #&& (steps.cache_sonar_scanner.outputs.cache-hit != 'true')
        run: |
          mkdir -p .sonar/scanner
          dotnet tool install --global dotnet-sonarscanner
        # --tool-path .sonar/scanner

      - name: 🔐 Build and analyze (Test ✅, Sonar ✅)
        if: ${{ inputs.unit_tests && inputs.sonar_qube }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"${{ vars.SONAR_ORGANIZATION }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml \
            /d:sonar.exclusions="${{ inputs.sonar_exclusions || ' '}}"
          dotnet restore ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj
          dotnet build ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj --no-incremental
          dotnet-coverage collect 'dotnet test ./src/' --output-format xml --output 'coverage.xml'
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: 🔐 Build and analyze (Test ⛔, Sonar ✅)
        if: ${{ !inputs.unit_tests && inputs.sonar_qube }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet-sonarscanner begin \
            /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"${{ vars.SONAR_ORGANIZATION }}" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.scanner.scanAll=false \
            /d:sonar.exclusions="${{ inputs.sonar_exclusions || ' '}}"
          dotnet restore ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj
          dotnet build ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj --no-incremental
          dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"

      - name: 🔐 Build and analyze (Test ✅, Sonar ⛔)
        if: ${{ inputs.unit_tests && !inputs.sonar_qube }}
        run: |
          dotnet-coverage collect 'dotnet test ./src/' -f xml -o 'coverage.xml'

      - name: ReportGenerator
        if: ${{ inputs.unit_tests }}
        uses: danielpalme/ReportGenerator-GitHub-Action@5
        with:
          reports: '**/*coverage.xml'
          targetdir: 'coveragereport'
          reporttypes: 'HtmlInline;Cobertura'
          assemblyfilters: '+*'
          classfilters: '-*.Migrations.*'
          filefilters: '+*'
          verbosity: 'Verbose'
          title: ${{ inputs.report_title }}
          tag: '${{ github.run_number }}_${{ github.run_id }}'
          toolpath: 'reportgeneratortool'

      - name: Upload coverage report artifact
        if: ${{ inputs.unit_tests }}
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/upload-artifact@main
        with:
          name: CoverageReport
          path: coveragereport

      - name: 🍵 Restore dependencies
        run: dotnet restore ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/${{ inputs.main_project }}.csproj

      - name: 🍵 Snyk Setup
        uses: snyk/actions/setup@master

      - name: 🍵 Run Snyk to check for vulnerabilities
        uses: snyk/actions/dotnet@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif --file=${{ inputs.project_base_dir }}/${{ inputs.sln }}

      - name: 🍵 Upload result to GitHub Code Scanning
        if: ${{ inputs.git_leaks }}
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: snyk.sarif

      - name: Write to workflow job summary
        run: |
          SUMMARY=$GITHUB_STEP_SUMMARY$'
          # Versão gerada\n
          | versao | data | 
          |--|--|
          | ${{ steps.get_version.outputs.tag }} | ${{ steps.get_env.outputs.now }} | \n
          Mensagem: ${{ inputs.msg_canal_deploy }}\n'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  check_image:
    name: Check if image exists
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    outputs:
      image_exists: ${{ steps.check_image_and_tag.outputs.IMAGE_EXISTS }}
    needs: build
    steps:
      - name: 🔍 Check if image exists in registry
        id: check_image_and_tag
        uses: felipementel/gh-actions/.github/actions/tools/docker/check-image@main
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          image_name: deploy.${{ inputs.image_name }}
          tag_version: ${{ needs.build.outputs.tag_version }}

  push_image:
    name: Push image to Registry
    environment: ${{ inputs.environment }}
    # if: ${{ github.event.pull_request.merged && github.event.pull_request.state == 'closed' }}
    needs: [build, check_image]
    runs-on: ubuntu-latest
    if: ${{ needs.check_image.outputs.image_exists == 'false' }}
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout
        uses: felipementel/gh-actions/.github/actions/_wrapper/github/checkout@main
        with:
          fetch_depth: 0
          sparse_checkout: |
            src
          sparse_checkout_cone_mode: false

      - name: 🐳 Docker Setup
        uses: felipementel/gh-actions/.github/actions/tools/docker/setup@main

      - name: 🐳 Docker Login
        uses: felipementel/gh-actions/.github/actions/tools/docker/login@main
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}

      - name: 🐳 Docker Build and Push
        uses: felipementel/gh-actions/.github/actions/tools/docker/buildx@main
        with:
          registry: ghcr.io
          registry_username: ${{ github.actor }}
          image_name: deploy.${{ inputs.image_name }}
          tag_version: ${{ needs.build.outputs.tag_version }}
          dockerfile: ${{ inputs.project_base_dir }}/${{ inputs.main_project }}/Dockerfile
          context: ${{ inputs.project_base_dir }}
          push: 'true'

      - name: Write to workflow job summary DEPLOY
        run: |
          SUMMARY=$'
          # Image publicada\n
          | versao | data | 
          |--|--|
          | ${{ needs.build.outputs.tag_version }} | ${{ needs.build.outputs.now }} | \n
          Mensagem: ${{ inputs.msg_canal_deploy }}\n'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  publish:
    name: Publish
    needs: [push_image]
    environment: ${{ inputs.environment }}
    # if: ${{ github.event.pull_request.merged && github.event.pull_request.state == 'closed' }}
    runs-on: ubuntu-latest
    steps:
      - name: Write to workflow job summary DEPLOY
        run: |
          SUMMARY=$'
          # Detalhes sobre publicação\n
          | versao | data | 
          |--|--|
          | ${{ needs.build.outputs.tag_version }} | ${{ needs.build.outputs.now }} | \n
          Mensagem: ${{ inputs.msg_canal_deploy }}\n'
          echo "$SUMMARY" >> $GITHUB_STEP_SUMMARY

  notify_image_exists:
    name: Notify when already image exists
    needs: [build, check_image]
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    if: ${{ needs.check_image.outputs.image_exists == 'true' }}
    steps:
      - name: Write to workflow job summary
        run: |
          echo "Image with tag ${{ needs.build.outputs.tag_version }} already exists. Skipping push image to registry and publish on Azure Cloud." >> $GITHUB_STEP_SUMMARY
